Repository milvus-io/milvus-sdk-cpp, pull requests merged in 2021-11, with the labels that each got.

#5 Setup initial project structure
  .gitignore
  CMakeLists.txt
  cmake/BuildUtils.cmake
  cmake/DefineOptions.cmake
  cmake/FindClangTools.cmake
  cmake/ThirdPartyPackages.cmake
  examples/example.md
  scripts/scripts.md
  src/CHANGELOG.md
  test/CHANGELOG.md
  thirdparty/thirdparty.md
Labels: ci-passed, approved, lgtm, size/S

#6 Add owner
  OWNERS
Labels: size/XS

#7 ci: add pipeline for build with ubuntu.
  .github/workflows/main.yaml
Labels: ci-passed, approved, lgtm, size/M

#9 Introduce cmake way to generate protocol pb.cc.
  scripts/proto_gen.sh
  src/CMakeLists.txt
  src/proto-gen/.gitignore
  src/proto-gen/proto-gen.cmake
Labels: ci-passed, approved, lgtm, size/M

#12 ci: porting cpplint/clang-format/clang-tidy from milvus-io/milvus
  .clang-format
  .clang-tidy
  .github/workflows/main.yaml
  .gitignore
  CMakeLists.txt
  scripts/cpplint.py
  scripts/install_deps.sh
  scripts/lint_exclusions.txt
  scripts/lintutils.py
  scripts/run_clang_format.py
  scripts/run_clang_tidy.py
  scripts/run_cpplint.py
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/include/MilvusClient.h
Labels: ci-passed, approved, lgtm, size/XXL

#19 Introducing unit testing framework.
  .github/workflows/main.yaml
  CMakeLists.txt
  Makefile
  cmake/DefineOptions.cmake
  cmake/ThirdPartyPackages.cmake
  scripts/build.sh
  test/CMakeLists.txt
  test/ut/TestDummy.cpp
Labels: ci-passed, approved, lgtm, size/L

#20 ci: add initial mergify configuration.
  .github/mergify.yml
  .github/workflows/main.yaml
Labels: ci-passed, approved, lgtm, size/S

#22 Refactoring milvus::Status
  src/impl/MilvusClientImpl.cpp
  src/impl/Status.cpp
  src/include/Status.h
  test/CMakeLists.txt
  test/ut/TestStatus.cpp
Labels: ci-passed, approved, lgtm, size/L
