Repository milvus-io/milvus-sdk-cpp, pull requests merged in 2021-12, with the labels that each got.

#26 Implement first api
  examples/simple/main.cpp
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/impl/MilvusConnection.cpp
  src/include/types/CollectionSchema.h
  src/include/types/DataType.h
  src/include/types/FieldSchema.h
Labels: ci-passed, approved, lgtm, size/L

#34 CI scripts improvements
  .github/workflows/main.yaml
  CMakeLists.txt
  cmake/FindClangTools.cmake
  examples/simple/main.cpp
  scripts/build.sh
  scripts/install_deps.sh
  scripts/lint_exclusions.txt
  scripts/run_cpplint.py
  src/CMakeLists.txt
  src/include/types/ConnectParam.h
  test/ut/TestDummy.cpp
  test/ut/TestStatus.cpp
Labels: ci-passed, approved, lgtm, size/M

#35 Refine the code style
  examples/simple/main.cpp
  src/impl/MilvusClientImpl.cpp
  src/impl/Status.cpp
  src/include/Status.h
  src/include/types/CollectionSchema.h
  src/include/types/FieldSchema.h
  src/include/types/TimeoutSetting.h
  test/ut/TestStatus.cpp
Labels: ci-passed, approved, lgtm, size/M

#37 Clang-tidy for naming
  .clang-tidy
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  src/include/Status.h
  test/ut/TestStatus.cpp
Labels: ci-passed, approved, lgtm, size/M

#39 Add HasCollection API.
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
  test/it/TestHasCollection.cpp
  test/it/mocks/MilvusMockedService.h
Labels: ci-passed, approved, lgtm, size/L

#48 Add interface for Create/Drop/Has partition
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
  test/it/TestCreateParition.cpp
  test/it/TestDropParition.cpp
  test/it/TestHasPartition.cpp
Labels: ci-passed, approved, lgtm, size/L

#50 Handle server side error
  src/impl/MilvusClientImpl.cpp
Labels: ci-passed, approved, lgtm, size/S

#53 Add ShowPartitions interface.
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
  src/include/types/PartitionInfo.h
  test/it/TestShowPartitions.cpp
Labels: ci-passed, approved, lgtm, size/L

#52 Add alias interfaces and index interfaces
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
  src/include/MilvusClient.h
  src/include/types/IndexDesc.h
  src/include/types/IndexState.h
Labels: ci-passed, approved, lgtm, size/L

#55 Support centos7 as builder
  .github/mergify.yml
  .github/workflows/main.yaml
  cmake/ThirdPartyPackages.cmake
  scripts/install_deps.sh
  test/it/mocks/MilvusMockedServer.cpp
Labels: ci-passed, approved, lgtm, size/M

#56 Add initial DEVELOPMENT.md guide
  DEVELOPMENT.md
Labels: ci-passed, approved, lgtm, size/M

#57 Fix typo Proto <- Proro
  src/impl/MilvusConnection.h
Labels: ci-passed, approved, lgtm, size/XS

#58 Refine mergify.yml
  .github/mergify.yml
Labels: ci-passed, approved, lgtm, size/S

#67 Implementation of LoadPartitions interface
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
  src/include/MilvusClient.h
  src/include/Status.h
  src/include/types/PartitionInfo.h
  src/include/types/TimeoutSetting.h
  test/it/TestLoadPartitions.cpp
Labels: ci-passed, approved, lgtm, size/L

#68 Define ProgressMonitor for sync interfaces
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/include/MilvusClient.h
  src/include/types/ProgressMonitor.h
  src/include/types/TimeoutSetting.h
  test/it/TestLoadPartitions.cpp
  test/ut/TestProgressMonitor.cpp
Labels: ci-passed, approved, lgtm, size/L, kind/improvement

#69 Add flush() for internal use
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
Labels: ci-passed, approved, lgtm, size/M, kind/improvement

#70 Add code coverage
  .github/workflows/main.yaml
  .gitignore
  CMakeLists.txt
  Makefile
  scripts/coverage.sh
  scripts/install_deps.sh
Labels: ci-passed, approved, lgtm, size/M, kind/improvement

#71 Refine implementation of LoadPartitions
  src/impl/MilvusClientImpl.cpp
  src/include/types/ProgressMonitor.h
  test/it/TestLoadPartitions.cpp
Labels: ci-passed, approved, lgtm, size/M

#72 Modify DEVELOPMENT.md
  DEVELOPMENT.md
Labels: kind/documentation, ci-passed, approved, lgtm, size/S

#74 Refein build scripts.
  .github/workflows/main.yaml
  CMakeLists.txt
  DEVELOPMENT.md
  cmake/FindClangTools.cmake
  cmake/ThirdPartyPackages.cmake
  scripts/coverage.sh
  scripts/install_deps.sh
  src/CMakeLists.txt
  src/proto-gen/proto-gen.cmake
  test/CMakeLists.txt
Labels: ci-passed, approved, lgtm, size/XL

#75 Fix for coverage scripts
  scripts/coverage.sh
Labels: ci-passed, approved, lgtm, size/XS

#76 Implementation of ReleasePartitions
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
  test/it/TestReleasePartitions.cpp
Labels: ci-passed, approved, lgtm, size/M

#73 Add CreateIndex() method
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  src/include/types/IndexDesc.h
  test/it/TestCreateIndex.cpp
Labels: ci-passed, approved, lgtm, size/M

#85 Refine lint jobs
  cmake/FindClangTools.cmake
  scripts/install_deps.sh
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
Labels: ci-passed, approved, lgtm, size/M

#86 Fix lint error on master
  src/impl/MilvusClientImpl.cpp
Labels: ci-passed, approved, lgtm, size/XS

#87 Implement of Insert interface.
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
  test/it/TestInsert.cpp
  test/it/TypeUtils.h
Labels: ci-passed, approved, lgtm, size/XL

#88 Prepare for search() and query()
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/include/MilvusClient.h
  src/include/types/FieldData.h
  src/include/types/QueryArguments.h
  src/include/types/QueryResults.h
  src/include/types/SearchArguments.h
  src/include/types/SearchResults.h
  test/ut/TestQueryArguments.cpp
  test/ut/TestSearchArguments.cpp
  test/ut/TestSearchResults.cpp
Labels: ci-passed, approved, lgtm, size/XL

#89 Add static library output
  examples/simple/CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
Labels: ci-passed, approved, lgtm, size/S

#99 Implement Query interface
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
  src/impl/TypeUtils.cpp
  src/impl/TypeUtils.h
  src/include/MilvusClient.h
  src/include/types/FieldData.h
  src/include/types/QueryArguments.h
  src/include/types/QueryResults.h
  test/CMakeLists.txt
  test/it/TestInsert.cpp
  test/it/TestQuery.cpp
  test/it/mocks/MilvusMockedServer.cpp
  test/it/mocks/MilvusMockedTest.cpp
Labels: ci-passed, approved, lgtm, size/XXL

#100 Implement Delete interface
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
  src/impl/TypeUtils.cpp
  src/impl/TypeUtils.h
  src/include/MilvusClient.h
  src/include/types/FieldData.h
  test/CMakeLists.txt
  test/it/TestDelete.cpp
  test/it/TypeUtils.h
  test/ut/TestTypeUtils.cpp
Labels: ci-passed, approved, lgtm, size/XL

#101 Update proto files
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/include/MilvusClient.h
  src/proto/common.proto
  src/proto/milvus.proto
Labels: ci-passed, approved, lgtm, size/M

#103 Implement Flush()
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
  src/include/MilvusClient.h
  src/include/types/ProgressMonitor.h
  test/it/TestFlush.cpp
  test/it/TestLoadPartitions.cpp
  test/it/mocks/MilvusMockedService.h
Labels: ci-passed, approved, lgtm, size/XL
