Repository milvus-io/milvus-sdk-cpp, pull requests merged in 2022-02, with the labels that each got.

#138 Add DescribeIndex Interface
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  src/include/milvus/types/IndexDesc.h
  test/it/TestDescribeIndex.cpp
Labels: ci-passed, approved, lgtm, size/L

#139 Use doxygen to generate documentation
  DEVELOPMENT.md
  Makefile
  doc/Doxyfile
Labels: ci-passed, approved, lgtm, size/XXL

#140 Refine the example
  examples/simple/main.cpp
  src/include/milvus/types/CollectionStat.h
  test/it/TestGetCollectionsStatistics.cpp
Labels: ci-passed, approved, lgtm, size/L

#142 Add create index tests
  test/it/TestCreateIndex.cpp
Labels: ci-passed, approved, lgtm, size/S

#143 Add drop index interface
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  test/it/TestDropIndex.cpp
Labels: ci-passed, approved, lgtm, size/M

#144 Add unittest cases
  test/ut/TestTypeUtils.cpp
Labels: ci-passed, approved, lgtm, size/L

#145 Some refinements for wait for status
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
Labels: ci-passed, approved, lgtm, size/M

#146 Add GetIndexBuildProgress interface
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  src/include/milvus/types/IndexState.h
  test/it/TestGetIndexBuildProgress.cpp
Labels: ci-passed, approved, lgtm, size/M

#148 Some refinements for CreateProtoFieldData
  src/impl/TypeUtils.cpp
Labels: ci-passed, approved, lgtm, size/M

#149 Support more redhat like platforms
  .github/workflows/main.yaml
  cmake/MilvusSdkPackagesLinux.cmake
  libmilvus.spec.rpkg
  scripts/install_deps.sh
Labels: ci-passed, approved, lgtm, size/L

#150 Increase code coverage to 99%
  src/impl/TypeUtils.cpp
  src/include/milvus/types/FieldSchema.h
  test/it/TestCreateIndex.cpp
  test/it/TestDescribeIndex.cpp
  test/it/TestSearch.cpp
  test/ut/TestTypeUtils.cpp
Labels: ci-passed, approved, lgtm, size/L

#152 Utils function for hybird timestamp
  src/include/milvus/MilvusClient.h
  src/include/milvus/types/Constants.h
  src/include/milvus/types/HybirdTimestamp.h
  test/ut/TestHybirdTimestamp.cpp
Labels: ci-passed, approved, lgtm, size/L

#154 Fix u_int64_t to uint64_t
  src/include/milvus/types/HybirdTimestamp.h
Labels: ci-passed, approved, lgtm, size/XS

#153 Update tested platform in development guide
  DEVELOPMENT.md
Labels: ci-passed, approved, lgtm, size/XS

#155 Add release pipeline on tag push
  .github/workflows/release.yaml
  scripts/build.sh
Labels: ci-passed, approved, lgtm, size/M
