Repository milvus-io/milvus-sdk-cpp, pull requests merged in 2022-01, with the labels that each got.

#104 Refactory for client implementation.
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
Labels: ci-passed, approved, lgtm, size/XL

#105 Support Ubuntu 20.04
  scripts/install_deps.sh
Labels: ci-passed, approved, lgtm, size/S

#106 Implement alias interfaces
  src/impl/MilvusClientImpl.cpp
  test/it/TestAlias.cpp
Labels: ci-passed, approved, lgtm, size/L, kind/improvement

#107 Add empty acceptance test
  .github/workflows/main.yaml
  CMakeLists.txt
  Makefile
  cmake/DefineOptions.cmake
  scripts/build.sh
  test/CMakeLists.txt
  test/st/MilvusDockerServer.cpp
  test/st/MilvusDockerServer.h
  test/st/MilvusServerTest.h
  test/st/TestCollection.cpp
Labels: ci-passed, approved, lgtm, size/L

#108 Implement Search interface (partial)
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
  src/impl/TypeUtils.cpp
  src/impl/TypeUtils.h
  src/include/MilvusClient.h
  src/include/types/SearchArguments.h
  src/include/types/SearchResults.h
  test/it/TestSearch.cpp
  test/ut/TestSearchResults.cpp
  test/ut/TestTypeUtils.cpp
Labels: ci-passed, approved, lgtm, size/L

#109 Implement compact interfaces
  examples/simple/main.cpp
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  src/impl/TypeUtils.cpp
  src/impl/TypeUtils.h
  src/include/types/CollectionDesc.h
  src/include/types/CollectionSchema.h
  src/include/types/CompactionPlan.h
  src/include/types/CompactionState.h
  src/include/types/Constants.h
  src/include/types/FieldSchema.h
  test/it/TestCompact.cpp
  test/it/TestDescribeCollection.cpp
  test/ut/TestCompactionPlan.cpp
  test/ut/TestCompactionState.cpp
  test/ut/TestFieldSchema.cpp
Labels: ci-passed, approved, lgtm, size/XL

#111 Add dropcollection interface
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  test/it/TestDropCollection.cpp
Labels: ci-passed, approved, lgtm, size/M

#114 Acceptance testing with create/drop collection.
  src/impl/MilvusConnection.h
  src/include/types/.CollectionSchema.h.un~
  src/include/types/CollectionSchema.h
  src/include/types/FieldSchema.h
  test/it/TestDescribeCollection.cpp
  test/st/MilvusDockerServer.cpp
  test/st/MilvusDockerServer.h
  test/st/MilvusServerTest.h
  test/st/TestCollection.cpp
  test/ut/TestFieldSchema.cpp
Labels: ci-passed, approved, lgtm, size/L

#113 Using googletest 1.11
  cmake/ThirdPartyPackages.cmake
Labels: ci-passed, approved, lgtm, size/XS

#115 Update guides for development
  DEVELOPMENT.md
Labels: ci-passed, approved, lgtm, size/M

#112 Add LoadCollection instant loading interface
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  test/it/TestLoadCollection.cpp
Labels: ci-passed, approved, lgtm, size/L

#116 Refine Search interface
  src/impl/MilvusClientImpl.cpp
  src/impl/TypeUtils.cpp
  src/impl/TypeUtils.h
  src/include/types/CollectionSchema.h
  src/include/types/SearchArguments.h
  src/include/types/SearchResults.h
  test/it/TestSearch.cpp
  test/st/MilvusServerTest.h
  test/st/TestSearch.cpp
  test/ut/TestSearchArguments.cpp
  test/ut/TestSearchResults.cpp
  test/ut/TestTypeUtils.cpp
Labels: ci-passed, approved, lgtm, size/XL

#118 Using MetricType from user input for Search
  src/impl/MilvusClientImpl.cpp
  src/impl/TypeUtils.cpp
  src/impl/TypeUtils.h
  src/include/types/MetricType.h
  src/include/types/SearchArguments.h
  test/it/TestSearch.cpp
  test/ut/TestTypeUtils.cpp
Labels: ci-passed, approved, lgtm, size/L

#122 Implement CalcDistance interfaces
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
  src/include/milvus/MilvusClient.h
  src/include/milvus/types/CalcDistanceArguments.h
  src/include/milvus/types/DataType.h
  src/include/milvus/types/DistanceArray.h
  test/it/TestCalcDistance.cpp
  test/ut/TestCalcDistanceArguments.cpp
Labels: ci-passed, approved, lgtm, size/XXL

#124 Fix codecov not working
  scripts/install_deps.sh
Labels: ci-passed, approved, lgtm, size/XS

#125 Build test for rpm package
  .github/workflows/main.yaml
  cmake/MilvusSdkPackagesLinux.cmake
  examples/CMakeLists.txt
  src/CMakeLists.txt
Labels: ci-passed, approved, lgtm, size/M

#127 Refine travel timestamp and guarantee timestamp for query/search
  examples/simple/main.cpp
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/include/milvus/MilvusClient.h
  src/include/milvus/types/Constants.h
  src/include/milvus/types/DmlResults.h
  src/include/milvus/types/QueryArguments.h
  src/include/milvus/types/SearchArguments.h
  src/proto/common.proto
  test/it/TestCreateCollection.cpp
  test/it/TestDelete.cpp
  test/it/TestInsert.cpp
  test/st/TestSearch.cpp
  test/ut/TestSearchArguments.cpp
  test/ut/TestSearchResults.cpp
  test/ut/TestTypeUtils.cpp
Labels: ci-passed, approved, lgtm, size/L

#128 Fix example bug
  .clang-tidy
  examples/simple/main.cpp
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusClientImpl.h
  src/include/milvus/MilvusClient.h
  src/include/milvus/types/ProgressMonitor.h
Labels: ci-passed, approved, lgtm, size/M

#129 Implement GetPartitionStatistics
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
  src/include/milvus/MilvusClient.h
  src/include/milvus/types/PartitionStat.h
  test/it/TestGetPartitionStatistics.cpp
  test/ut/TestPartitionStat.cpp
Labels: ci-passed, approved, lgtm, size/L

#130 Refine scripts for get cpu count under macOS
  scripts/build.sh
Labels: ci-passed, approved, lgtm, size/XS

#131 Implememnt GetMetrics interface
  src/impl/MilvusClientImpl.cpp
  test/it/TestGetMetrics.cpp
Labels: ci-passed, approved, lgtm, size/M

#132 Add deb package under Ubuntu
  .github/workflows/main.yaml
  cmake/MilvusSdkPackagesLinux.cmake
  scripts/install_deps.sh
Labels: ci-passed, approved, lgtm, size/L

#133 Promote milvus 2.0.0 for system testing
  test/st/MilvusDockerServer.cpp
Labels: ci-passed, approved, lgtm, size/XS

#134 GetPersistentSegmentInfo interface
  src/impl/MilvusClientImpl.cpp
  src/impl/TypeUtils.cpp
  src/impl/TypeUtils.h
  test/it/TestGetPersistentSegmentInfo.cpp
  test/ut/TestTypeUtils.cpp
Labels: ci-passed, approved, lgtm, size/L

#135 LoadBalance/GetQuerySegmentInfo interface
  src/impl/MilvusClientImpl.cpp
  src/impl/TypeUtils.cpp
  src/impl/TypeUtils.h
  test/it/TestGetQuerySegmentInfo.cpp
  test/it/TestLoadBalance.cpp
Labels: ci-passed, approved, lgtm, size/L

#136 Add release collection interface
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  test/it/TestRelseaseCollection.cpp
Labels: ci-passed, approved, lgtm, size/M

#137 Add GetCollectionStatistics() interface
  src/impl/MilvusClientImpl.cpp
  src/impl/MilvusConnection.cpp
  src/impl/MilvusConnection.h
  src/include/milvus/types/CollectionStat.h
  test/it/TestGetCollectionsStatistics.cpp
Labels: ci-passed, approved, lgtm, size/L
